apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: vuejs
  template:
    metadata:
      labels:
        component: vuejs
    spec:
      containers:
        - name: vuejs
          image: ghcr.io/panagiotis-bellias-it21871/ref-letters-vuejs-client
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: vuejs-config
          imagePullPolicy: Always